import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "DKB Scuba",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className='min-h-screen'>{children}</div>
        <footer className='bg-black p-4 text-white'>
          <ul className='flex justify-center items-center gap-5'>
            <li>contact</li>
            <li>terms</li>
            <li>about</li>
          </ul>
        </footer>
      </body>
    </html>
  );
}
