import type { Metadata } from "next";
import "./globals.css";
import AuthButton from "./components/auth-button";
import { NavLinks } from '@/app/ui/nav-links'

export const metadata: Metadata = {
  title: "DKB Scuba",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <NavLinks />
        <main>
          <div className="container">{children}</div>
        </main>
        <footer>
          <div className="footer-content">
              <a href="#contact">Contact</a>
              <a href="#terms">Terms</a>
              <a href="#about">About</a>
          </div>
        </footer>
      </body>
    </html>
  );
}
